sources:
  - name: News
    handler:
      openapi:
        source: https://developer-lostark.game.onstove.com/swagger-doc/endpoints/news
        operationHeaders:
          Authorization: '{context.headers.authorization}'
  - name: Characters
    handler:
      openapi:
        source: https://developer-lostark.game.onstove.com/swagger-doc/endpoints/characters
        operationHeaders:
          Authorization: '{context.headers.authorization}'
  - name: Armories
    handler:
      openapi:
        source: https://developer-lostark.game.onstove.com/swagger-doc/endpoints/armories
        operationHeaders:
          Authorization: '{context.headers.authorization}'
  - name: Auctions
    handler:
      openapi:
        source: https://developer-lostark.game.onstove.com/swagger-doc/endpoints/auctions
        selectQueryOrMutationField:
          - fieldName: 'Auctions_GetItems' # OAS field name
            type: Query # switch method POST from default Mutation into Query
        operationHeaders:
          Authorization: '{context.headers.authorization}'
  - name: Guilds
    handler:
      openapi:
        source: https://developer-lostark.game.onstove.com/swagger-doc/endpoints/guilds
        operationHeaders:
          Authorization: '{context.headers.authorization}'
  - name: Markets
    handler:
      openapi:
        source: https://developer-lostark.game.onstove.com/swagger-doc/endpoints/markets
        operationHeaders:
          Authorization: '{context.headers.authorization}'

documents:
  - documents/*.graphql